Repository pomerium/cli, pull requests merged in 2021-11, with the labels that each got.

#6 Fix docs link
  README.md
Labels: docs

#8 deployment: migrate pomerium-cli automation to new repo
  .github/dependabot.yaml
  .github/workflows/backport.yaml
  .github/workflows/release.yaml
  goreleaser.yaml
Labels: deployment

#11 cli: make the commands actually work
  Makefile
  cmd/pomerium-cli/api.go
  cmd/pomerium-cli/cache.go
  cmd/pomerium-cli/kubernetes.go
  cmd/pomerium-cli/main.go
  cmd/pomerium-cli/tcp.go
  cmd/pomerium-cli/version.go
  go.sum
  version/version.go
  version/version_test.go
Labels: bug

#10 deployment: docker image and build commands
  .github/workflows/docker-main.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.release
  Makefile
  goreleaser.yaml
Labels: deployment
