Repository pomerium/cli, pull requests merged in 2022-01, with the labels that each got.

#25 close active listener when removing connection
  api/config_server.go
  api/listener_server_test.go
  go.sum
Labels: bug

#27 deployment: multi-arch main image
  .github/workflows/docker-main.yaml
  Dockerfile
  Dockerfile.release
  goreleaser.yaml
Labels: deployment

#28 ci: fix lint during image build
  Dockerfile
  Makefile
Labels: ci

#29 add sentry and signal handlers
  cmd/pomerium-cli/api.go
  cmd/pomerium-cli/main.go
  go.mod
  go.sum
  proto/log.go
Labels: improvement

#30 fix empty tags
  api/config.go
  api/config_test.go
Labels: bug

#31 deployment: fix multiarch release
  .github/workflows/release.yaml
  goreleaser.yaml
Labels: bug, deployment
