Repository pomerium/cli, pull requests merged in 2022-05, with the labels that each got.

#60 bump core to 0.17.2
  go.mod
  go.sum
Labels: dependencies

#56 Add proxy command
  cmd/pomerium-cli/proxy.go
  go.mod
  go.sum
Labels: enhancement, accepted

#68 proxy cmd hidden
  cmd/pomerium-cli/proxy.go
Labels: enhancement

#69 bump core to 0.17.3
  cmd/pomerium-cli/databroker.go
  go.mod
  go.sum
Labels: dependencies

#72 bump go 1.18
  .github/workflows/test.yaml
  Makefile
  go.mod
  go.sum
Labels: dependencies
